### ISSUE TITLE
Semi-implemented tests

### ISSUE THREAD

**Issue by nsgonultas** [joaoventura/pylibui#19]
There are some tests with a single raise keyword and a TODO comment. They are failing. I think they must be commented out until a way to simulate mouse press found or... what about removing them completely? Because I don't think we can find a way to simulate mouse press.

Instead of tests we can request working examples that uses the functions which need mouse input from contributors.

**Comment by joaoventura** [comment]
I would leave tests and continue to implement them as to make sure we do not break functionalities in the future. However, I do agree to remove tests that need user interaction, as I currently do not know of any way to simulate it.

We should keeping requesting examples (because they show how the API is working on a higher level) and tests (without user interaction, of course).
